#!/usr/bin/env python
import os

def is_raw(f):
    return f.endswith('.NEF') or f.endswith('.nef')

def has_jpg(f, files):
    base = os.path.splitext(f)[0]
    return (base + '.jpg') in files or (base + '.JPG') in files

files = os.listdir('.')
nefs_to_delete = filter(lambda f: is_raw(f) and has_jpg(f, files), files)
print '\n'.join(nefs_to_delete)
yn = raw_input('Do you want to delete those files: y/N? ')
if yn.strip() in ['Y', 'y']:
    print 'Deleting...'
[os.remove(f) for f in nefs_to_delete]
