#!/bin/bash
read line

if [ -z "$line" ]; then
    echo "Empty input." >&2
    exit 1
fi

echo "$line"  >&2
echo "size:  " `du -h "$line" | cut -f1`  >&2
echo "width: " `video-width "$line"` >&2
echo `realpath "$line"` > /tmp/echo-and-open-previous
open "$line"
