#!/bin/sh
function quiet_killall {
	killall "$1" 2>&1 | fgrep -v 'No matching processes belonging to you were found'
}
quiet_killall Dropbox
quiet_killall Last.fm
quiet_killall 'Last.fm Scrobbler'
quiet_killall Skype
quiet_killall LimeChat
quiet_killall Spotify
quiet_killall iTunes
quiet_killall 'Mailplane 3'
quiet_killall Mail
quiet_killall 1Password
quiet_killall Airfoil
quiet_killall HipChat
quiet_killall Cloudup
quiet_killall Transmission
brightness 0.1
