#!/bin/sh
function quiet_killall {
	killall "$1" 2>&1 | fgrep -v 'No matching processes belonging to you were found'
}
quiet_killall Dropbox
quiet_killall Last.fm
quiet_killall 'Last.fm Scrobbler'
quiet_killall Skype
quiet_killall LimeChat
quiet_killall Spotify
quiet_killall iTunes
quiet_killall 'Mailplane 3'
quiet_killall Mail
quiet_killall 1Password
quiet_killall '1Password 5'
quiet_killall Airfoil
quiet_killall HipChat
quiet_killall Slack
quiet_killall Cloudup
quiet_killall Transmission
quiet_killall iPhoto
quiet_killall Twitter
quiet_killall Fantastical
quiet_killall Messages
quiet_killall 'CleanMyMac 3 Menu'
quiet_killall Telegram
quiet_killall Sonos
quiet_killall Dash
quiet_killall Reminders
quiet_killall Screenhero
quiet_killall zoom.us
brightness 0.1
blueutil --power 0
