#!/usr/bin/env python
import os
import re
import sys
import webbrowser

def usage():
    print_err('\nUsage:', sys.argv[0], ' [<path>]')
    sys.exit(2)

def escape_shell_arg(s):
    return "'" + s.replace("'", "'\\''") + "'"

def print_err(*items):
    sys.stderr.write(' '.join(map(str, items))+'\n')

trac_base_from_svn_base_urls = {
	'https://core.svn.wordpress.org/': 'http://core.trac.wordpress.org/browser/',
	'https://svn.automattic.com/wordpress': 'http://core.trac.wordpress.org/browser/',
    'https://svn.glotpress.org/': 'http://trac.glotpress.org/browser/',
	'https://unit-tests.svn.wordpress.org/': 'http://core.trac.wordpress.org/browser/tests/',
}

def trac_url_from_svn_url(svn_url):
    for svn_base_url in trac_base_from_svn_base_urls:
        if svn_url.startswith(svn_base_url):
            return svn_url.replace(svn_base_url, trac_base_from_svn_base_urls[svn_base_url])

def main(target = '.'):
    info = os.popen('svn info %s' % target).read()
    m = re.search(r'URL:\s*(.*)$', info, re.M)
    if not m or not m.group(1):
        print_err('SVN URL not found!')
        sys.exit(3)
    svn_url = m.group(1)
    trac_url = trac_url_from_svn_url(svn_url)
    try:
        webbrowser.open(trac_url)
    except webbrowser.Error, e:
        print_err(e)
        print trac_url


if __name__ == '__main__':
    target = '.'
    if len(sys.argv) > 1:
        target = sys.argv[1]
    main(target)
