#!/bin/sh
max_depth=5
cwd=`pwd`
declare -i depth
depth=0
found=1

base_dir=$1 || '.'
shift 1

cd $base_dir
while [[ ! -f phpunit.xml && ! -f phpunit.xml.dist ]]
do
	depth+=1
	cd ..
	if [[ $depth > $max_depth ]]
	then
		found=0
		break
	fi
done
if [[ $found == 1 ]]
then
	if [ -f phpunit.xml.dist ]; then
		config_file_name=phpunit.xml.dist
	else
		config_file_name=phpunit.xml
	fi
	if grep -q 'colors="true"' $config_file_name; then
		perl -pne 's/colors="true"/colors="false"/' $config_file_name > .$config_file_name
		config_file_name=".$config_file_name"
	fi
	echo Using `pwd`/$config_file_name
	phpunit -c $config_file_name "$@"
	cd $cwd
	exit 0
else
	echo "ERROR: could not find phpunit.xml within $max_depth levels up"
	cd $cwd
	exit 1
fi
