#!/bin/bash
# check arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: $(basename "$0") <start hh:mm:ss> <end hh:mm:ss> <input file> <output file>"
    exit 1
fi
ffmpeg -ss "$1" -to "$2" -i "$3" -c copy "$4"